### ISSUE TITLE
Critipu Flaw CVSS 10.0 found

### ISSUE THREAD

**Issue by TheCyberViking** [AlanTheBlank/AlanTheBlank#1]
I discuvwed a fucky wucky on youw git, you awe missying contenty on this gity and the text is uwu enough

![image](https://user-images.githubusercontent.com/22121899/87949038-6916ce80-ca9d-11ea-960e-7d9870fb9cc8.png)

**Comment by TheCyberViking** [comment]
twis could end u up in the foreverbox if no patchypoo

**Comment by McLabraid** [comment]
![image](https://user-images.githubusercontent.com/18464829/88676213-b6b9b980-d0e3-11ea-98a2-dac13e2d94de.png)

**Comment by AlanTheBlank** [comment]
![ETZeFm](https://user-images.githubusercontent.com/12967303/88676241-be795e00-d0e3-11ea-94fc-ed495b2fb8da.gif)
